### ISSUE TITLE
Does the django-bakery version still need to be be pinned at 0.12.7?

### ISSUE THREAD

**Issue by stevejalim** [wagtail/wagtail-bakery#43]
Thanks for this project - it's very handy!

`wagtail-bakery` currently requires `django-bakery==0.12.3`, which is now more than a year old. 

Is it pinned to that because `wagtail-bakery` will break on higher versions, please? (Or is it just a very understandable matter of the maintainers being busy? :smile: ) 

Cheers
Steve

**Comment by loicteixeira** [comment]
Given that Django-Bakery is still in beta (version `0.x`), I can understand why the dependency was pinned. However, looking at the changelog, I see no reason not to upgrade to 0.12.7. I would even say to open it a little bit with `~=0.12.7`.

Would you mind creating a PR with that change and we can see how the tests play out? I'm aming for a new release of Wagtail-Bakery mid-October.

**Comment by loicteixeira** [comment]
Fixed in #44
